### PR TITLE
update to Unicode 8.0.0

### PR DESCRIPTION
**Pull request by novelplus**
I'm working on writing a text layout/rendering library and noticed the algorithm updates for Unicode 8.0.0 were fairly straightforward to implement, so I went ahead and patched them in.  Let me know if you have any questions or need me to do anything else.

GitHub username and email are fine for the ChangeLog.

### CODE REVIEW

**Comment by tasn** [comment]
It looks good on the wordbreak front, I assume you just ran the database update script, is that correct? If so, we're good.

@adah1972, please take a look at the linebreak part.

Thanks for your contribution!

**Comment by adah1972** [comment]
It looks very nice! Thanks.

Please allow me to find a free time to have a test and write a change log entry. I do not expect any issues, though.

Care to give your real name, unless you really do not want to show it? I still prefer real names.

**Comment by novelplus** [comment]
Yes, that is exactly what I did.

Would initials be acceptable?  Prefer not to have my name out, but AKV is fine.

**Comment by adah1972** [comment]
If you do not want your real name shown, I think novelplus is OK. It looks better than AKV.

**Comment by adah1972** [comment]
Merged. I only added an EOL at the end of test.txt, and also a change log entry.

**Pull request merged**
